version: "3.8"

services:
    reddis:
        container_name: redis_container
        image: redis:6.2.3-alpine
        ports:
            - 6379:6379

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 12345
        ports:
            - 5432:5432
